groups:
 - name: InstanceDown
   interval: 5s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: InstanceDown
     expr: up == 0
     for: 5m
     labels:
       severity: page
     annotations:
       summary: "Instance {{ $labels.instance }} down"
       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

 
 - name: NFVI Services_status
   interval: 30s
   rules:
   - alert: NFVI Service is down
     expr: avg_over_time(collectd_nfvi_service{job="collectd",service!~"zombieprocess-process"}[30s])==0
     for: 30s
     labels:
       severity: critical
     annotations:
       summary: NFVi service is down
       description: "NFVi service has been DOWN for more than 30 secs."
       
   - alert: Zombie process(es)
     expr: avg_over_time(collectd_nfvi_service{job="collectd",service="zombieprocess-process"}[30s])>0
     for: 30s
     labels:
       severity: critical
     annotations:
       summary: "{{ $value }} zombie process(es) found"
       description: "{{ $value }} zombie process(es) for more than 30 secs."
   - alert: System Rebooted
     expr: collectd_uptime{job="collectd"}<{{ system_rebooted_interval }}
#    for: {{ system_rebooted_for_time }}
     labels:
       severity: critical
     annotations:
       summary: "{% raw %}{{ $labels.instance }}{% endraw %} rebooted"
       description: "{% raw %}{{ $labels.instance }}{% endraw %} rebooted."
    

