groups:
 - name: InstanceDown
   interval: 5s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: InstanceDown
     expr: up == 0
     for: 5m
     labels:
       severity: page
     annotations:
       summary: "Instance {{ $labels.instance }} down"
       description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

 
 - name: NFVI Services_status
   interval: 30s
   rules:
   - alert: NFVI Service is down
     expr: avg_over_time(collectd_nfvi_service{job="collectd",service!~"zombieprocess-process"}[30s])==0
     for: 30s
     labels:
       severity: critical
     annotations:
       summary: NFVi service is down
       description: "NFVi service has been DOWN for more than 30 secs."
       
   - alert: Zombie process(es)
     expr: avg_over_time(collectd_nfvi_service{job="collectd",service="zombieprocess-process"}[30s])>0
     for: 30s
     labels:
       severity: critical
     annotations:
       summary: "{{ $value }} zombie process(es) found"
       description: "{{ $value }} zombie process(es) for more than 30 secs."
   - alert: System Rebooted
     expr: collectd_uptime{job="collectd"}< 60
#    for: {{ system_rebooted_for_time }}
     labels:
       severity: critical
     annotations:
       summary: "{% raw %}{{ $labels.instance }}{% endraw %} rebooted"
       description: "{% raw %}{{ $labels.instance }}{% endraw %} rebooted."
   - name: COLLECTD_DOWN
   interval: 1s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: Collectd_down
     #expr: absent(sa_collectd_uptime) // this cant be predicted
     expr: sa_collectd_last_metric_for_host_status==0
     for: 20s
     labels:
       severity: critical
     annotations:
       summary: "collectd in {{ $labels.source}} is down or no data"
       description: "collectd  is not sending data from {{ $labels.source }} is has been down for more than 20s secs."

 - name: QPID_DOWN
   interval: 1s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: qpid_router_down
     #expr: absent(sa_collectd_uptime)
     expr: sa_collectd_qpid_router_status==0
     for: 10s
     labels:
       severity: critical
     annotations:
       summary: "qpid dispatch router in  {{ $labels.instance}} is down"
       description: "qpid dispatch router may have connection error is not sending data from {{ $labels.instance }} is has been down for more than 10s minutes."

 - name: ElasticSearch_Down
   interval: 1s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: elasticsearch_down
     #expr: absent(sa_collectd_uptime)
     expr: sa_collectd_elasticsearch_status==0
     for: 10s
     labels:
       severity: critical
     annotations:
       summary: "ElasticSearch {{ $labels.instance}} is down"
       description: "ElasticSearch may have connection error in  {{ $labels.instance }} is has been down for more than 10s"

 - name: telemetry_listener_high_latency
   interval: 1s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: telemetry_listerner_slow
     #expr: absent(sa_collectd_uptime)
     expr: floor(sa_collectd_last_pull_timestamp_seconds)-time()>6
     for: 10s
     labels:
       severity: critical
     annotations:
       summary: "{{$labels.source}} running in {{ $labels.instance}}  is slow "
       description: "{{$labels.source}}  running in {{ $labels.instance }}  having high latency "

 - name: telemetry_listener_down
   interval: 1s
   rules:
   # Alert for any instance that is unreachable for >5 minutes.
   - alert: telemetry_listerner_down
     #expr: absent(sa_collectd_uptime)
     expr: absent(sa_collectd_last_pull_timestamp_seconds)
     for: 20s
     labels:
       severity: critical
     annotations:
       summary: "Either metirc or event listener running in {{ $labels.instance}} is dead"
       description: "Either metirc or event listener running in {{ $labels.instance }} is dead"
    

