# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 35s # Evaluate rules every 15 seconds. The default is every 1 minute.
  #scrape_timeout is set to the global default (10s).
  scrape_timeout: 5s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 10.19.110.5:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'prometheus.rules.yml'
  - 'alert.rules.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  #aputtur's test node  
  - job_name: 'collectd'

    #scrape_interval: 5s
    scrape_interval: 5s

    file_sd_configs:
      - files:
        - 'nodes/nodespoc.yml'
  #Openstack node
  - job_name: 'openstack'
    scrape_interval: 5s

    static_configs:
      - targets: ['10.19.110.233:19103']	


