---
- name: Enable RHEL testing repos on all hosts
  hosts: OSEv3
  become: yes
  tasks:
  # - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Server or Red Hat Virtualization
  #  redhat_subscription:
  #    state: present
  #    activationkey: "key-name"
  #    org_id: 1111111
  #    pool: '^(Red Hat Cloud Suite|Red Hat OpenShift Container Platform)$'

  - name: Same as above but subscribe to a specific pool by ID.
    redhat_subscription:
      state: present
      username: aputtur@redhat.com
      password: 
      pool_ids: 8a85f98260c27fc50160c323263339ff

      #8a85f98260c27fc50160c323247e39e0 
  - name: Disable all current yum repos
    rhsm_repository:
      name: '*'
      state: disabled

  - name: Enable Repositories
    rhsm_repository:
      name: "{{ item }}"
      state: enabled
    with_items:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ansible-2.4-rpms
      - rhel-7-server-ose-3.9-rpms
      - rhel-7-fast-datapath-rpms
