---
openshift_openstack_clusterid: "openshift"
openshift_openstack_public_dns_domain: "mycomlab.com"
#openshift_openstack_dns_nameservers: ["10.11.5.19"]
openshift_openstack_dns_nameservers: ["10.19.111.158"]

openshift_openstack_public_hostname_suffix: "-public"


openshift_openstack_external_nsupdate_keys:
  private:
    key_secret: "BTm/zfJ/XrLJLiLbgVQBy2sDxCKQr3ZAAD2KrEA+Y5Y="
    key_algorithm: "HMAC-SHA256"
    key_name: "public-openshift.mycomlab.com"
    server: "10.19.111.158"
  public:
    key_secret: "BTm/zfJ/XrLJLiLbgVQBy2sDxCKQr3ZAAD2KrEA+Y5Y="
    key_algorithm: "HMAC-SHA256"
    key_name: "public-openshift.mycomlab.com"
    server: "10.19.111.158"

# # Used Hostnames
# # - set custom hostnames for roles by uncommenting corresponding lines
openshift_openstack_master_hostname: "master"
openshift_openstack_infra_hostname: "infranode"
#openshift_openstack_cns_hostname: "cns"
openshift_openstack_node_hostname: "appnode"
#openshift_openstack_lb_hostname: "lb"
openshift_openstack_etcd_hostname: "etcd"

openshift_openstack_keypair_name: "ocpkp"
openshift_openstack_external_network_name: "public_network"
openshift_openstack_private_network_name:  "private_network" 
#"openshift-ansible-{{ openshift_openstack_stack_name }}-net"
# # A dedicated Neutron network name for containers data network
# # Configures the data network to be separated from openshift_openstack_private_network_name
# # NOTE: this is only supported with Flannel SDN yet
#openstack_private_data_network_name: "openshift-ansible-{{ openshift_openstack_stack_name }}-data-net"

## Kuryr networking
# TODO: Allow the user to specify pre-existing subnets for pod and services
#openshift_openstack_kuryr_service_subnet_cidr: "172.30.0.0/16"

## You should set the following if you want to use Kuryr/Neutron as your SDN
openshift_use_kuryr: False
openshift_use_openshift_sdn: True

# NOTE: you must uncomment these for Kuryr to work properly as well:
#openshift_master_open_ports:
#- service: dns tcp
#  port: 53/tcp
#- service: dns udp
#  port: 53/udp
#openshift_node_open_ports:
#- service: dns tcp
#  port: 53/tcp
#- service: dns udp
#  port: 53/udp

use_trunk_ports: True
os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
openshift_node_proxy_mode: userspace
# # Kuryr needs to have the pod based registry (if desired in the cluster)
# deployed after kuryr is up and running. This can be done with oadm
# #Disable management of the OpenShift Registry
#openshift_hosted_manage_registry: false

# # Kuryr needs to know the network or the subnet you will be taking Floating
# IPs for the loadbalancer services from.
# kuryr_openstack_public_net_id: uuid_of_my_fip_net
#kuryr_openstack_public_net_id: <Public network ID>
# If you have different subnet at the Floating IP network you can also specify
# it but need to ensure default policy allows your tennat to retrieve that
# information
# kuryr_openstack_public_subnet_id: uuid_of_my_fip_subnet

#openshift_openstack_kuryr_controller_image: docker-registry.engineering.redhat.com/rhosp13/openstack-kuryr-controller:latest
#openshift_openstack_kuryr_cni_image: docker-registry.engineering.redhat.com/rhosp13/openstack-kuryr-cni:latest

# If you VM images will name the ethernet device different than 'eth0',
# override this
#kuryr_cni_link_interface: eth0

## Ports pooling is enabled by default (with nested driver).
## To disable, uncomment the next:
#kuryr_openstack_pool_driver: noop
#
## You can also alter the port pooling defaults here
#kuryr_openstack_pool_max: 0
#kuryr_openstack_pool_min: 1
#kuryr_openstack_pool_batch: 5
#kuryr_openstack_pool_update_frequency: 20
#
## You can pre-populate the pools with subports by uncommenting the next line
## and specifying the amount of subports you want to pre-create per
## origin-node, e.g.: openshift_kuryr_precreate_subports: 5
#openshift_kuryr_precreate_subports: 5
#
## You can also change the default device owner for the precreated subports
#openshift_kuryr_device_owner: compute:kuryr
#
# You can also disable the kuryr controller and cni healthcheck probes by
# uncommenting the next
#enable_kuryr_controller_probes: False
#enable_kuryr_cni_probes: False


## If you want to use a provider network, set its name here.
## NOTE: the `openshift_openstack_external_network_name` and
## `openshift_openstack_private_network_name` options will be ignored when using a
## provider network.
#openshift_openstack_provider_network_name: "provider"

# # Used Images
# # - set specific images for roles by uncommenting corresponding lines
# # - note: do not remove openshift_openstack_default_image_name definition
#openshift_openstack_master_image_name: "centos7"
#openshift_openstack_infra_image_name: "centos7"
#openshift_openstack_cns_image_name: "centos7"
#openshift_openstack_node_image_name: "centos7"
#openshift_openstack_lb_image_name: "centos7"
#openshift_openstack_etcd_image_name: "centos7"
openshift_openstack_default_image_name: "rhel75a"

openshift_openstack_num_masters: 1
openshift_openstack_num_infra: 1
openshift_openstack_num_cns: 0
openshift_openstack_num_nodes: 2

# # Used Flavors
# # - set specific flavors for roles by uncommenting corresponding lines
# # - note: do note remove openshift_openstack_default_flavor definition
openshift_openstack_master_flavor: "ocpmaster"
openshift_openstack_infra_flavor: "ocpinfranode"
#openshift_openstack_cns_flavor: "m1.medium"
openshift_openstack_node_flavor: "ocpappnode"
#openshift_openstack_lb_flavor: "m1.medium"
openshift_openstack_etcd_flavor: "medium.1"
openshift_openstack_default_flavor: "ocpappnode"

# # Numerical index of nodes to remove
# openshift_openstack_nodes_to_remove: []


## Select a load balancer solution you desire. Only one of these can be
## `true` at a time. If they're both `false`, no load balancer will be deployed.
openshift_openstack_use_lbaas_load_balancer: false
openshift_openstack_use_vm_load_balancer: false


# # Docker volume size
# # - set specific volume size for roles by uncommenting corresponding lines
# # - note: do not remove docker_default_volume_size definition
#openshift_openstack_docker_master_volume_size: "15"
#openshift_openstack_docker_infra_volume_size: "15"
#openshift_openstack_docker_cns_volume_size: "15"
#openshift_openstack_docker_node_volume_size: "15"
#openshift_openstack_docker_etcd_volume_size: "2"
#openshift_openstack_docker_lb_volume_size: "5"
openshift_openstack_docker_volume_size: "15"

## Specify server group policies for master and infra nodes. Nova must be configured to
## enable these policies. 'anti-affinity' will ensure that each VM is launched on a
## different physical host.
#openshift_openstack_master_server_group_policies: [anti-affinity]
#openshift_openstack_infra_server_group_policies: [anti-affinity]


# The Classless Inter-Domain Routing (CIDR) for the OpenStack VM subnet.
openshift_openstack_subnet_cidr: "172.69.1.0/24"
# The starting IP address for the OpenStack subnet allocation pool.
openshift_openstack_pool_start: "172.69.1.2"
# The ending IP address for the OpenStack subnet allocation pool.
openshift_openstack_pool_end: "172.69.1.254"

## Red Hat subscription:
#rhsub_user: '<username>'
#rhsub_pass: '<password>'
#rhsub_pool: '<pool name>'


# # Roll-your-own DNS
#openshift_openstack_external_nsupdate_keys:
#  public:
#    server: "<DNS server IP>"
#    key_name: "public-openshift.example.com"
#    key_algorithm: "HMAC-SHA256"
#    key_secret: "<key for DNS updates>"
#  private:
#    server: "<DNS server IP>"
#    key_name: "public-openshift.example.com"
#    key_algorithm: "HMAC-SHA256"
#    key_secret: "<key for DNS updates>"


# NOTE(shadower): Do not change this value. The Ansible user is currently
# hardcoded to `openshift`.
ansible_user: openshift

# Resolve heat stack outputs. Disabling outputs helps stack scalability. (default: True)
#openshift_openstack_resolve_heat_outputs: True

# # Use a single security group for a cluster (default: false)
#openshift_openstack_flat_secgrp: true

# If you want to use the VM storage instead of Cinder volumes, set this to `true`.
# NOTE: this is for testing only! Your data will be gone once the VM disappears!
openshift_openstack_ephemeral_volumes: false

## cloud config
openshift_openstack_disable_root: true
openshift_openstack_user: openshift
